steps:
# Fetch the source code
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/stashconsulting/hashicorp-terraform-docker.git']

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/terraform-docker:$SHORT_SHA', '.']
