steps:
# Fetch the source code
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/stashconsulting/hashicorp-terraform-docker.git']

# Access the secret version in Secret Manager and store it in a file
- name: gcr.io/cloud-builders/gcloud
  entrypoint: 'bash'
  args: [ '-c', 'gcloud secrets versions access latest --secret=secret-data > decrypted-data.txt' ]

# Use decrypted-data.txt to login to a private Docker registry
- name: gcr.io/project-test-270001/terraform-docker:0.1
  entrypoint: 'bash'
  args: [ '-c', 'docker login --username=glad23 --password-stdin < decrypted-data.txt']
