steps:
# Fetch the source code
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/stashconsulting/hashicorp-terraform-docker.git']

# Using terraform Docker image
- name: 'gcr.io/project-test-270001/terraform-docker'
  id: init
  args: ['init']

# Create the resources using Terraform
- name: 'gcr.io/project-test-270001/terraform-docker'
  id: Build
  args: ['apply']  
